version: '3.8'

services:
  client:
    build:
      context: ./client 
      dockerfile: dockerfile 
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./client:/app
      - /app/node_modules 
    command: npm start 

  server:
    build:
      context: ./server 
      dockerfile: dockerfile 
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./server:/app
      - /app/node_modules 
    command: npm run dev
