# Use the official Node.js 20 image.
FROM node:20

# Set the working directory.
WORKDIR /app

# Copy package.json and package-lock.json files.
COPY package*.json ./

# Install dependencies.
RUN npm install

# Copy the rest of the application code.
COPY . .

# Set the environment variable to development.
ENV NODE_ENV=development

# Expose the port for the backend.
EXPOSE 4000

# Start the application.
CMD ["npm", "run", "dev"]
