export const GET_ALL_CONNECT_MAILS_REQUEST = "GET_ALL_CONNECT_MAILS_REQUEST"
export const GET_ALL_CONNECT_MAILS_SUCCESS = "GET_ALL_CONNECT_MAILS_SUCCESS"
export const GET_ALL_CONNECT_MAILS_FAIL = "GET_ALL_CONNECT_MAILS_FAIL"

export const GET_INBOX_MAILS_REQUEST = "GET_INBOX_MAILS_REQUEST"
export const GET_INBOX_MAILS_SUCCESS = "GET_INBOX_MAILS_SUCCESS"
export const GET_INBOX_MAILS_FAIL = "GET_INBOX_MAILS_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"